apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movies
  name: movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      volumes:
        - name: db-volume
          configMap:
            name: movies-db
      containers:
        - image: us.icr.io/iac-registry/movies:1.0
          name: movies
          volumeMounts:
            - name: db-volume
              mountPath: /data
