apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: IMAGE
          resources:
            requests:
              memory: "320Mi"
              cpu: "200m"
            limits:
              memory: "400Mi"
              cpu: "200m"
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  ports:
    - port: 9080
  type: ClusterIP
  selector:
    app: test
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  tls:
    - hosts:
        - HOST
      secretName: SECRET 
  rules:
    - host: HOST
      http:
        paths:
          - path: /autoscale-webapp
            backend:
              serviceName: test
              servicePort: 9080
